/**
 * @module utils/toolLibraryGenerator
 * @description Generates and parses Fusion 360 compatible JSON tool libraries.
 */

import { NUMBER_DRILLS, LETTER_DRILLS, METRIC_DRILLS, FRACTIONAL_DRILLS } from './drills';

/**
 * Generates a Fusion 360 Tool Library JSON object.
 * @param {Object} workshop - The workshop configuration from app state.
 * @param {Object} allCalculatedThreads - Map of standardId -> array of thread objects (from App.jsx).
 * @param {Object} metadata - Build metadata (version, commitHash).
 * @returns {Object} Fusion 360 compatible JSON.
 */
export const generateToolLibrary = (workshop, allCalculatedThreads = {}, metadata = {}) => {
    const { version = '0.0.0', commitHash = 'unknown' } = metadata;
    const tools = [];

    // 1. Process Drills
    const drillSets = {
        'Metric': METRIC_DRILLS,
        'Number': NUMBER_DRILLS,
        'Letter': LETTER_DRILLS,
        'Imperial': FRACTIONAL_DRILLS
    };

    workshop.enabledDrillSets.forEach(setName => {
        const drills = drillSets[setName] || [];
        drills.forEach(drill => {
            if (!workshop.disabledDrills.includes(drill.name)) {
                tools.push(createDrillTool(drill));
            }
        });
    });

    // 2. Process Custom Drills
    workshop.customDrills.forEach(drill => {
        tools.push(createDrillTool(drill));
    });

    // 3. Process Taps (Curated Thread Sizes)
    workshop.enabledStandards.forEach(stdId => {
        const threads = allCalculatedThreads[stdId] || [];
        const disabled = workshop.disabledDesignations[stdId] || [];
        const custom = workshop.customDesignations[stdId] || [];

        // Add enabled presets
        threads.forEach(t => {
            if (!disabled.includes(t.designation)) {
                tools.push(createTapTool(t, stdId));
            }
        });

        // Add custom designations
        custom.forEach(c => {
            if (c.enabled !== false) {
                tools.push(createTapTool(c, stdId));
            }
        });
    });

    return {
        "version": "1.0",
        "description": `Generated by Fusion 360 Thread Generator (https://matthewmcneill.github.io/FusionThreadsGenerator) - Version: ${version} (${commitHash})`,
        "data": tools
    };
};

/**
 * Creates a unique GUID for a tool.
 * @returns {string}
 */
const generateGuid = () => {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
};

const createDrillTool = (drill) => {
    const diameterMm = drill.sizeMm || (drill.size * 25.4);

    // Scale geometry based on diameter
    const lcf = Math.max(25, diameterMm * 3); // Cutting length ~3x diameter
    const lb = lcf + Math.max(5, diameterMm * 0.5); // Length below holder
    const oal = lb + 25; // Overall length

    return {
        "guid": generateGuid(),
        "type": "drill",
        "description": drill.name,
        "unit": "millimeters",
        "geometry": {
            "DC": diameterMm,
            "LB": lb,
            "LCF": lcf,
            "OAL": oal,
            "tip-angle": 118
        },
        "start-values": [
            {
                "guid": generateGuid(),
                "description": "Default",
                "values": {
                    "spindle-speed": 1000,
                    "feed-vertical": 50,
                    "feed-plunge": 50
                }
            }
        ],
        "post-process": {
            "number": 0,
            "comment": "Imported from FusionThreadsGenerator"
        }
    };
};

const createTapTool = (thread, stdId) => {
    // FIX: Use thread.basic.major if available, otherwise fallback to size calculation
    const basicMajor = thread.basic?.major;
    const diameterMm = basicMajor !== undefined ? basicMajor : (thread.sizeMm || (thread.size * 25.4));
    const pitchMm = thread.pitch || (25.4 / thread.tpi);

    // Scale geometry based on diameter
    const lcf = Math.max(20, diameterMm * 2.5);
    const lb = lcf + Math.max(10, diameterMm * 1);
    const oal = lb + 30;

    const isCustom = thread.type === 'custom' || !thread.basic; // Custom threads often lack full basic object or are marked

    return {
        "guid": generateGuid(),
        "type": "tap-right-hand",
        "description": `${thread.designation} (${stdId})${isCustom ? ' [Custom]' : ''}`,
        "unit": "millimeters",
        "geometry": {
            "DC": diameterMm,
            "TP": pitchMm,
            "LB": lb,
            "LCF": lcf,
            "OAL": oal,
            "thread-profile-angle": 55 // Most British standards are 55
        },
        "start-values": [
            {
                "guid": generateGuid(),
                "description": "Default",
                "values": {
                    "spindle-speed": 500,
                    "feed-vertical": pitchMm * 500, // Synchronized tapping feed
                    "feed-plunge": pitchMm * 500
                }
            }
        ],
        "post-process": {
            "number": 0,
            "comment": `Imported from FusionThreadsGenerator - ${stdId}`
        }
    };
};

/**
 * Parses a Fusion 360 Tool Library JSON and returns a partial workshop configuration.
 * @param {string} jsonStr - The JSON content from the file.
 * @param {string} strategy - 'merge' or 'overwrite'.
 * @param {Object} currentWorkshop - The current workshop configuration.
 * @returns {Object} Updated workshop configuration.
 */
export const parseToolLibrary = (jsonStr, strategy, currentWorkshop, allPresets = {}) => {
    try {
        const lib = JSON.parse(jsonStr);
        if (!lib.data || !Array.isArray(lib.data)) {
            throw new Error("Invalid tool library format: 'data' array missing.");
        }

        const newWorkshop = strategy === 'overwrite'
            ? {
                enabledStandards: [],
                enabledDrillSets: [],
                disabledDrills: [],
                customDrills: [],
                disabledDesignations: {},
                customDesignations: {}
            }
            : JSON.parse(JSON.stringify(currentWorkshop));

        // In overwrite mode, we want 100% fidelity. 
        // We'll pre-fill disabled lists with EVERYTHING we know about,
        // and then remove them as we find them in the file.
        if (strategy === 'overwrite') {
            // For each standard we have presets for, assume it's disabled unless found
            Object.keys(allPresets).forEach(stdId => {
                newWorkshop.disabledDesignations[stdId] = allPresets[stdId].map(p => p.designation);
                newWorkshop.customDesignations[stdId] = [];
            });

            // For drills, we'll enable sets as we find them. 
            // We'll pre-fill disabledDrills with all standard bits across all sets.
            const allSets = {
                'Metric': METRIC_DRILLS,
                'Number': NUMBER_DRILLS,
                'Letter': LETTER_DRILLS,
                'Imperial': FRACTIONAL_DRILLS
            };
            Object.values(allSets).forEach(drills => {
                drills.forEach(d => {
                    if (!newWorkshop.disabledDrills.includes(d.name)) {
                        newWorkshop.disabledDrills.push(d.name);
                    }
                });
            });
        }

        const stats = { drills: 0, taps: 0, ignored: 0, total: lib.data.length };

        lib.data.forEach(tool => {
            if (tool.type === 'drill') {
                if (importDrill(tool, newWorkshop)) {
                    stats.drills++;
                } else {
                    stats.ignored++;
                }
            } else if (tool.type === 'tap-right-hand' || tool.type === 'tap-left-hand') {
                if (importTap(tool, newWorkshop, allPresets)) {
                    stats.taps++;
                } else {
                    stats.ignored++;
                }
            } else {
                stats.ignored++;
            }
        });

        return { workshop: newWorkshop, stats };
    } catch (e) {
        console.error("Failed to parse tool library:", e);
        throw e;
    }
};

const importDrill = (tool, workshop) => {
    const diameterMm = tool.geometry?.DC;
    if (diameterMm === undefined) return false;

    const diameterIn = diameterMm / 25.4;

    // Check if it matches a standard drill
    const allSets = {
        'Metric': METRIC_DRILLS,
        'Number': NUMBER_DRILLS,
        'Letter': LETTER_DRILLS,
        'Imperial': FRACTIONAL_DRILLS
    };

    let found = false;
    for (const [setName, drills] of Object.entries(allSets)) {
        const match = drills.find(d => Math.abs(d.size - diameterIn) < 0.0001);
        if (match) {
            // Enable the set
            if (!workshop.enabledDrillSets.includes(setName)) {
                workshop.enabledDrillSets.push(setName);
            }
            // Ensure it's not disabled
            workshop.disabledDrills = workshop.disabledDrills.filter(name => name !== match.name);
            found = true;
            return true;
        }
    }

    if (!found) {
        // Add to custom drills if not already there
        const alreadyExists = workshop.customDrills.find(d => Math.abs(d.size - diameterIn) < 0.0001);
        if (!alreadyExists) {
            workshop.customDrills.push({
                name: tool.description || `Drill ${diameterMm.toFixed(2)}mm`,
                size: diameterIn,
                sizeMm: diameterMm,
                unit: 'mm',
                type: 'custom'
            });
        }
    }
    return true;
};

const importTap = (tool, workshop, allPresets) => {
    const description = tool.description || "";
    // Format: "Designation (StandardId) [Custom]"
    const match = description.match(/^(.*?)\s*\(([^)]+)\)(\s*\[Custom\])?$/);

    if (match) {
        const designation = match[1].trim();
        const stdId = match[2].trim();
        const isCustom = !!match[3];

        if (!workshop.enabledStandards.includes(stdId)) {
            workshop.enabledStandards.push(stdId);
        }

        if (isCustom) {
            // Add to custom designations for this standard if not already there
            if (!workshop.customDesignations[stdId]) {
                workshop.customDesignations[stdId] = [];
            }
            const exists = workshop.customDesignations[stdId].find(c => c.designation === designation);
            if (!exists) {
                workshop.customDesignations[stdId].push({
                    designation,
                    size: (tool.geometry?.DC || 0) / 25.4,
                    sizeMm: tool.geometry?.DC || 0,
                    pitch: tool.geometry?.TP || 0,
                    tpi: tool.geometry?.TP ? (25.4 / tool.geometry.TP) : 0,
                    enabled: true,
                    type: 'custom'
                });
            }
            return true;
        }

        // Try to enable this specific designation if it was disabled
        if (workshop.disabledDesignations[stdId]) {
            workshop.disabledDesignations[stdId] = workshop.disabledDesignations[stdId].filter(d => d !== designation);
        }
        return true;
    } else {
        // Fallback: search across all presets by diameter and pitch
        const diameterMm = tool.geometry?.DC;
        const pitchMm = tool.geometry?.TP;
        if (diameterMm !== undefined && pitchMm !== undefined) {
            const diameterIn = diameterMm / 25.4;
            const tpi = 25.4 / pitchMm;

            for (const [stdId, presets] of Object.entries(allPresets)) {
                const matchPreset = presets.find(p =>
                    Math.abs(p.size - diameterIn) < 0.001 &&
                    (p.pitch ? Math.abs(p.pitch - pitchMm) < 0.001 : Math.abs(p.tpi - tpi) < 0.1)
                );

                if (matchPreset) {
                    if (!workshop.enabledStandards.includes(stdId)) {
                        workshop.enabledStandards.push(stdId);
                    }
                    if (workshop.disabledDesignations[stdId]) {
                        workshop.disabledDesignations[stdId] = workshop.disabledDesignations[stdId].filter(d => d !== matchPreset.designation);
                    }
                    return true;
                }
            }
        }
    }
    return false;
};
