/**
 * @module utils/xmlGenerator
 * @description Generates Fusion 360 compatible XML files (.xml) for thread definitions.
 * 
 * @exports
 * - generateFusionXML: Orchestrates the conversion of thread objects to XML.
 */

/**
 * Escapes special XML characters in a string value so it is safe to embed in XML text nodes.
 * The `&` replacement must occur first to avoid double-escaping subsequent entities.
 *
 * @param {*} value - The value to escape (will be coerced to string).
 * @returns {string} The XML-safe escaped string.
 */
const escapeXml = (value) =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

/**
 * Generates the full XML string for a thread standard with version metadata.
 * Processes threads and their associated tolerance classes into Fusion 360's schema.
 *
 * @param {Object} threadStandard - Metadata about the standard (name, unit, angle, etc.).
 * @param {Array<Object>} threads - Array of calculated thread size objects.
 * @param {Array<string>} selectedClasses - List of class names to include in the output.
 * @param {Object} metadata - Build metadata (version, commitHash).
 * @returns {string} The formatted XML content.
 */
export const generateFusionXML = (threadStandard, threads, selectedClasses, metadata = {}) => {
  const { version = '0.0.0', commitHash = 'unknown' } = metadata;

  // 1. Construct the XML Header with standard metadata and tool info
  const header = `<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Generated by Fusion 360 Thread Generator
  https://matthewmcneill.github.io/FusionThreadsGenerator
  Version: ${version} (${commitHash})
-->
<ThreadType>
  <Name>${escapeXml(threadStandard.name)}</Name>
  <CustomName>${escapeXml(threadStandard.name)}</CustomName>
  <Unit>${threadStandard.unit}</Unit>
  <Angle>${threadStandard.angle}</Angle>
  <SortOrder>${threadStandard.sortOrder}</SortOrder>
  <ThreadForm>${threadStandard.threadForm}</ThreadForm>`;

  // 2. Determine if we use Pitch (Metric) or TPI (Imperial)
  const isMetric = threadStandard.unit === 'mm';

  // 3. Group threads by nominal size (Fusion 360 groups by <Size>)
  const groupedThreads = threads.reduce((acc, thread) => {
    const size = thread.size.toString();
    if (!acc[size]) acc[size] = [];
    acc[size].push(thread);
    return acc;
  }, {});

  // 4. Generate each <ThreadSize> block
  const body = Object.entries(groupedThreads).map(([size, sizeThreads]) => {
    const designations = sizeThreads.map(t => {
      const pitchElement = isMetric
        ? `<Pitch>${t.basic.p}</Pitch>`
        : `<TPI>${t.tpi}</TPI>`;

      // Generate <Thread> blocks for both internal and external genders for each class.
      // Fusion 360 expects separate blocks for each gender+class combination.
      const threadBlocks = selectedClasses
        .filter(className => t.classes[className]) // Ensure the class exists for this thread
        .map(className => {
          const c = t.classes[className];
          const blocks = [];

          if (c.external) {
            blocks.push(`
        <Thread>
          <Gender>external</Gender>
          <Class>${escapeXml(className)}</Class>
          <ThreadToleranceClass>${escapeXml(className)}</ThreadToleranceClass>
          <MajorDia>${c.external.major}</MajorDia>
          <PitchDia>${c.external.pitch}</PitchDia>
          <MinorDia>${c.external.minor}</MinorDia>
        </Thread>`);
          }

          if (c.internal) {
            // Internal (Nut) thread geometry.
            // Note: TapDrill is conditionally added if it passed base validation.
            blocks.push(`
        <Thread>
          <Gender>internal</Gender>
          <Class>${escapeXml(className)}</Class>
          <ThreadToleranceClass>${escapeXml(className)}</ThreadToleranceClass>
          <MajorDia>${c.internal.major}</MajorDia>
          <PitchDia>${c.internal.pitch}</PitchDia>
          <MinorDia>${c.internal.minor}</MinorDia>${(c.internal.tapDrillToolSize && !c.internal.tapDrillValidation?.status?.startsWith('catastrophic')) ? `
          <TapDrill>${c.internal.tapDrillToolSize}</TapDrill>` : ''}
        </Thread>`);
          }

          return blocks.join('');
        }).join('');

      return `
      <Designation>
        <ThreadDesignation>${escapeXml(t.designation)}</ThreadDesignation>
        <CTD>${escapeXml(t.ctd || t.designation)}</CTD>
        ${pitchElement}
        ${threadBlocks}
      </Designation>`;
    }).join('');

    return `
    <ThreadSize>
      <Size>${size}</Size>
      ${designations}
    </ThreadSize>`;
  }).join('');

  // 5. Append the closing tag and return the complete document
  const footer = `
</ThreadType>`;

  return header + body + footer;
};
